// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/mood-tracker": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/food-log": {
    params: {};
  };
  "/journal": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/mood-tracker" | "/dashboard" | "/food-log" | "/journal" | "/profile" | "/*";
  };
  "routes/[mood-tracker]._index.jsx": {
    id: "routes/[mood-tracker]._index";
    page: "/mood-tracker";
  };
  "routes/[dashboard]._index.jsx": {
    id: "routes/[dashboard]._index";
    page: "/dashboard";
  };
  "routes/[food-log]._index.jsx": {
    id: "routes/[food-log]._index";
    page: "/food-log";
  };
  "routes/[journal]._index.jsx": {
    id: "routes/[journal]._index";
    page: "/journal";
  };
  "routes/[profile]._index.jsx": {
    id: "routes/[profile]._index";
    page: "/profile";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};